cargo clippy -- \
    -Wclippy::all \
    -Wclippy::restriction \
    -Wclippy::correctness \
    -Wclippy::pedantic \
    -Wclippy::nursery \
    -Wclippy::cargo \
    -Wclippy::suspicious \
    -Wclippy::complexity \
    -Wclippy::style \
    -Wclippy::perf
